version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - db:/db
    expose:
      - '5432:5432'
    networks:
      - transcendNetwork
    env_file:
      - .env

  daphne:
    build:
      context: ./requirements/Daphne
    container_name: daphne
    image: daphne
    restart: always
    volumes:
      - app:/app
    expose:
      - "8001"
    networks:
      - transcendNetwork
    depends_on:
      - postgres
      - pong
    env_file:
      - .env

  nginx:
    build:
      context: ./requirements/Nginx
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "44433:44433"
    volumes:
      - app:/app
    networks:
      - transcendNetwork
    depends_on:
      - postgres

  pong:
    build:
      context: ./requirements/Pong-Server
    container_name: pong
    image: pong
    restart: always
    ports:
      - "8765-8790:8765-8790"
    networks:
      - transcendNetwork
    volumes:
      - app:/app
    depends_on:
      - nginx

volumes:
  app:
    driver: local
    name: app
    driver_opts:
      o: bind
      type: none
      device: ./django_code
  db:
    driver: local
    name: db
    driver_opts:
      o: bind
      type: none

networks:
  transcendNetwork:
    driver: bridge
    name: transcendNetwork
