# Generated by Django 5.0.4 on 2024-06-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login42',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
