# Generated by Django 5.0.4 on 2024-06-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_login42'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='a2f',
            field=models.BooleanField(default=False),
        ),
    ]
