# Generated by Django 5.0.4 on 2024-06-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_a2f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='a2f',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
