# Generated by Django 5.0.4 on 2024-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='a2f_secret',
            field=models.TextField(default='W2FFQGITOGS2BQVOIHVZUWA3YJ4SFW6O'),
        ),
    ]
