# Generated by Django 5.0.4 on 2024-06-25 14:34

import pyotp
import transcend.views.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_a2f_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='a2f_secret',
            field=models.TextField(default=pyotp.random_base32),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[transcend.views.utils.validate_alphanumeric]),
        ),
    ]
