# Generated by Django 5.0.4 on 2024-06-25 14:34

import transcend.views.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_channel_remove_membership_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, validators=[transcend.views.utils.validate_alphanumeric]),
        ),
    ]
