# Generated by Django 3.2.8 on 2024-02-28 10:38

from django.db import migrations, models
from django.db.models.functions import Now


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=25)),
                ('avatar', models.TextField(blank=True, default='')),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('bot', models.BooleanField(null=True, default=False)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, blank=True)),
            ],
        ),
    ]
