# Generated by Django 3.2.8 on 2024-03-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=-10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='pseudo',
            field=models.TextField(max_length=25),
        ),
    ]
