# Generated by Django 5.0.4 on 2024-05-31 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_membership_channel_remove_message_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='match',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
