# Generated by Django 3.2.8 on 2024-03-20 16:23

from django.db import migrations, models
from django.db.models.functions import Now


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240320_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('owner', models.ForeignKey(on_delete=models.deletion.DO_NOTHING, to='users')),
                ('created_at', models.DateTimeField(auto_now_add=True, blank=True, default=Now())),
                ('updated_at', models.DateTimeField(auto_now_add=True, blank=True, default=Now())),
            ]
        )
    ]
