# Generated by Django 3.2.8 on 2024-03-20 16:25

from django.db import migrations, models
from django.db.models.functions import Now


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240320_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('channel_id', models.ForeignKey(on_delete=models.deletion.DO_NOTHING, to='channels')),
                ('user_id', models.ForeignKey(on_delete=models.deletion.DO_NOTHING, to='User')),
                ('created_at', models.DateTimeField(auto_now_add=True, blank=True, default=Now())),
            ],
        ),
    ]
