# Generated by Django 3.2.8 on 2024-03-20 16:29

from django.db import migrations, models
from django.db.models.functions import Now


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240320_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='channel_user',
            fields=[
                ('channel', models.ForeignKey(on_delete=models.deletion.DO_NOTHING, to='channels')),
                ('user', models.ForeignKey(on_delete=models.deletion.DO_NOTHING, to="users.user")),
                ('joined_at', models.DateTimeField(auto_now_add=True, blank=True, default=Now())),
            ]
        )
    ]
